GET https://localhost:60008/people

###

GET https://localhost:60008/vaccinelist

###

POST  https://localhost:60008/addperson
content-type: application/json

{
    "firstName": "Lucas",
    "lastName": "Locatelli"
}

###

GET  https://localhost:60008/addvaccine/1/tetanus


###

DELETE https://localhost:60008/DeletePerson/3


###

GET https://localhost:60008/GoodBye/0